version: 2
jobs:

  dockerhub-push:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          sh dockerhub_push.sh zirra/facerecognition

  deploy-azure:
    docker:
      - image: azuresdk/azure-cli-python:2.0.23
    steps:
      - run: |
          az login --service-principal -u $K8S_SERVICE_PRINCIPAL_USERNAME --password $K8S_SERVICE_PRINCIPAL_PASSWORD --tenant $K8S_SERVICE_PRINCIPAL_TENANT
          az aks install-cli
          az aks get-credentials -g datasys-qa -n datasys-qa

          if [ ! -z "$CIRCLE_BRANCH" ]; then
            UNIQUEID=$CIRCLE_BRANCH-$CIRCLE_SHA1
            kubectl set image deployments/facerecognition facerecognition=zirra/facerecognition:$UNIQUEID
          fi

          if [ ! -z "$CIRCLE_TAG" ]; then
            UNIQUEID=release-$CIRCLE_TAG
            kubectl set image deployments/facerecognition facerecognition=zirra/facerecognition:$UNIQUEID
          fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - dockerhub-push:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /pull\/.*/
#      - deploy-azure:
#          requires:
#            - dockerhub-push
#          filters:
#            tags:
#              only:
#                - /v[0-9]+(\.[0-9]+)*/
#            branches:
#              only:
#                - master
#                - webapp_integration
#                - experimental
